### ISSUE TITLE
How to test

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/lorawan-webhook-templates#16]
#### Summary

The readme states:
> When submitting a new Webhook template or making changes to an existing one, please make sure the integration defined by it works correctly.

What is the recommended method to test a new webhook?

Is the intention that one should install a private Things Stack instance, load the templates, and test in that way?

#### How do you propose to implement this?

Document how to test a webhook.

#### Can you do this yourself and submit a Pull Request?

Updating the readme yes, but I need the required information first.

**Comment by jpmeijers** [comment]
### Test wehbook template

If the steps to install a private TTS instance using docker-compose was followed (https://www.thethingsindustries.com/docs/getting-started/installation/), one can do this to get webhook templates working.

In the same directory as the `docker-compose.yml` file, clone the webhooks:
`git clone https://github.com/TheThingsNetwork/lorawan-webhook-templates.git`

In `docker-compose.yml` link the webhooks in as a volume:
```
    volumes:
      - ./blob:/srv/ttn-lorawan/public/blob
      - ./config/stack:/config:ro
      - ./lorawan-webhook-templates:/lorawan-webhook-templates:ro
      # If using Let's Encrypt:
      - ./acme:/var/lib/acme
```

In `ttn-lw-stack-docker.yml` add a config for the wehokk template path
```
as:
  mqtt:
    public-address: 'https://<redacted>:1883'
    public-tls-address: 'https://<redacted>:8883'
  webhooks:
    downlink:
      public-address: '<redacted>:1885/api/v3'
    templates:
      directory: 'lorawan-webhook-templates'
```

Add your webhook template according to [the docs](https://www.thethingsindustries.com/docs/integrations/webhooks/webhook-templates/adding_webhook_templates/).

Restart the stack with:
```
docker-compose stop stack
docker-compose up -d
```

Your webhook should be available.

### Comments

* I'm not sure if the stack needs to be restarted to get updates for the webhook to appear on the console. Sometimes they appeared directly, other times they didn't. I restart the stack to be safe.

* Having to run a full TTS instance just to test a webhook template is a little overkill. It would be nice if there was a more lightweight manner in which one can test this.
