### ISSUE TITLE
Default value ignored

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/lorawan-webhook-templates#18]
#### Summary

I have a default value defined in the template:
```
fields:
  - id: experiment
    name: Experiment Name (optional)
    description: If you are testing (new device, balloon flights, etc) and do not want your data to appear on the main map, please specify an experiment name.
    secret: false
    default-value: "test"
```

But on the console the field is not filled in with the default value:

![image](https://user-images.githubusercontent.com/948278/109270162-4fe5b580-7816-11eb-8201-85a7fac06205.png)

#### Environment
- **Webhook template:** new
- **The Things Stack version:** v3.11.1

#### Steps to Reproduce

1. Add a field to the webhook template
2. Add a default value
3. Reload console / restart stack

#### What do you see now?

Field is not pre-filled with default value

#### What do you want to see instead?

The field should be pre-filled with the default value

#### How do you propose to implement this?

Fix the bug

#### Can you do this yourself and submit a Pull Request?

No
