### ISSUE TITLE
Only uplink-message endpoint added

### ISSUE THREAD

**Issue by jpmeijers** [TheThingsNetwork/lorawan-webhook-templates#20]
#### Summary

In my-template.yaml I have:
```
paths:
  uplink-message: /uplink-message
  join-accept: /join-accept
  location-solved: /location-solved
```

But when the webhook is added, only the uplink-message endpoint was added:
![image](https://user-images.githubusercontent.com/948278/111585554-293cee00-87c8-11eb-8ac1-59e317e75af0.png)

#### Environment
- **Webhook template:** new under development
- **The Things Stack version:** v3.11.2

#### Steps to Reproduce

1. Create a template that adds more than just the uplink-message enpoints.
2. Create a webhook from the tempalte.
3. Look at which endpoints are active.

#### What do you see now?

Only uplink-message is added.

#### What do you want to see instead?

All defined endpoints in the template should be added.

#### How do you propose to implement this?

Fix the bug.

#### Can you do this yourself and submit a Pull Request?

No
